name: Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [12, 14]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Node.js ${{matrix.node}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}
      - name: Install & Build
        run: yarn install
      - name: Prepare Build
        run: |
          cp ./run.me blst/bindings/node.js/run.me
          cp blst_wrap.cpp blst/bindings/node.js/blst_wrap.cpp
        name: run.me
        run: ./run.me
        working-directory: blst/bindings/node.js
      - name: Post build
        run: cp blst/bindings/node.js/blst.node build/blst.node
      - name: Test
        run: yarn test
