name: Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        # windows-latest disabled by now, unable to build
        os: [ubuntu-latest, macos-latest]
        node: [10, 11, 12, 13, 14]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Node.js ${{matrix.node}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}

      - name: Setup SWIG
        run: |
          git clone -b pr/new-node-fixes https://github.com/yegorich/swig;
          cd swig;
          ./autogen.sh;
          ./configure --prefix=$HOME/swig;
          make;
          make install;

      - name: Run.me
        run: |
          env PATH=~/swig/bin:$PATH SWIG_LIB=~/swig/share/swig/4.0.2 \
            ./blst/bindings/node.js/run.me
          cp blst/bindings/node.js/blst_wrap.cpp build/blst_wrap_${{matrix.os}}_${{matrix.node}}.cpp

      - name: Install deps
        run: yarn install --ignore-scripts
      - name: Build TS
        run: yarn build
      - name: Build bindings
        run: yarn install
        env:
          IGNORE_SWIG_PREBUILT: true
      - name: Test
        run: yarn test

      - name: Upload bindings
        uses: actions/upload-artifact@v2
        if: github.repository_owner == 'chainsafe' && github.event_name != 'pull_request'
        with:
          name: binding.node
          path: build/
